### ISSUE TITLE
Associated Legendre Polynomials

### ISSUE THREAD

**Issue by raminammour** [JuliaApproximation/FastTransforms.jl#101]
Hello,

I was evaluating some spherical harmonics implementations and found the implementation here to be competitive with GSL for example (which is great!). Looking at the function `sphevaluate` it is easy to see that hidden inside would be an implementation of the associated Legendre polynomials.

The codes does a few extra flops (division/multiplication by pi, cos/sin) and the usual obscure normalization factors :)

It would be great the associated Legendre polynomial can be pulled out, and exported from this package. Maybe even contributed to some other julia package (SpecialFunctions?). It would be a very competitive pure julia implementation.

Any help is appreciated, and thanks for a nice package,

Cheers!

**Comment by raminammour** [comment]
Sorry about the noise, just found: https://github.com/JuliaMath/SpecialFunctions.jl/pull/136

**Comment by dlfivefifty** [comment]
That PR looks like it’s going nowhere. If you wanted to pull this out and make a new PR that might fair better.

**Comment by raminammour** [comment]
Sorry, I meant this one https://github.com/JuliaMath/SpecialFunctions.jl/pull/175, which looks more promising :)

**Comment by MikaelSlevinsky** [comment]
The Clenshaw--Smith recurrence relation (evaluating expansions with bases satisfying three-term recurrence relations) is a perfect candidate for vectorization since it costs O(mn) flops but only requires O(m+n) storage to evaluate an m-term expansion at n points. One day, I may add such generic code in the C library this wraps using Intel SIMD so that they're `ccall`able.
