### ISSUE TITLE
Switch to BinaryBuilder.jl

### ISSUE THREAD

**Issue by ranocha** [JuliaApproximation/FastTransforms.jl#170]
Would you consider switching to [BinaryBuilder.jl](https://github.com/JuliaPackaging/BinaryBuilder.jl)? We experienced problems with new Apple M1 devices due to the build script of FastTransforms.jl, see https://github.com/trixi-framework/Trixi.jl/pull/1104#discussion_r841006607

CC @sloede

**Comment by MikaelSlevinsky** [comment]
FastTransforms.jl has FastTransforms_jll.jl with [binaries for M1 Macs](https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/tag/FastTransforms-v0.5.4%2B1). The BinaryProvider route is only for developer support to allow compiling from source.

Maybe it's that the build script always gets invoked and it sees that it's `using BinaryProvider` for some diagnostic functions?

**Comment by MikaelSlevinsky** [comment]
Tagging a new minor release based on this https://github.com/JuliaApproximation/FastTransforms.jl/commit/4bbefc9ad453d9405c2d482caaa01cf366279d36. Probably will work for you, but let me know if it doesn't.

**Comment by sloede** [comment]
Thank you for looking into it. Unfortunately, it does not solve all issues. Here I tried adding FastTransforms.jl in a temporary project:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/3637659/161587266-90ff0a85-ea97-4f3c-b6c7-60587e54cf88.png">

Weirdly enough, it says precompilation succeeded, but also that it didn't. Maybe the issue is, that BinaryProvider.jl is still in the dependency list in `Project.toml`?

**Comment by MikaelSlevinsky** [comment]
This ought to do it https://github.com/JuliaApproximation/FastTransforms.jl/commit/ee31e98707915c3f4a8aa86c015cd1917cf5a448.

**Comment by ranocha** [comment]
I can only second that - thank you very much!
