### ISSUE TITLE
Building requires `sudo` privileges

### ISSUE THREAD

**Issue by mfherbst** [JuliaApproximation/FastTransforms.jl#84]
Right now building FastTransforms requires root or sudo privileges on Linux machines. This is a deal-breaker for installing on shared cluster infrastructures, where one does just not have this. Also IMHO, running `sudo` from an install script coming from a git repository is a very bad idea as I would not consider this a trusted source.

Other Packages like FFTW use [BinaryProvider.jl](https://github.com/JuliaPackaging/BinaryProvider.jl) for binary dependencies. Is there any reason, which prevents use of that package?

**Comment by MikaelSlevinsky** [comment]
Yes, please see this issue https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/442.

On Julia < v1.3, this won't be possible because the Julia's gcc doesn't ship with the compiler support library `libgomp`. On Julia v1.3+, I was hoping to get this working but there is an issue with `using CompilerSupportLibraries_jll` at the moment (at least on macOS) regarding locating the libraries that are part of the artifact.

Note that the most recent tag is still a pure Julia package; the C library dependency is only on master right now. Systems programming is not my *forte*, so PRs to this package and/or the C library are welcome.

**Comment by mfherbst** [comment]
@MikaelSlevinsky Sorry, I should've looked for issues in BinaryProvider first ... my bad. Thanks for the clarification and the link to the PR :smile:. I can't promise anything, but if I manage to find the time, I'll have a go at the build script.

**Comment by dlfivefifty** [comment]
You’ll make me extremely happy if you do! Build issues are the reason that we haven’t tagged, which is limiting us from handling spherical harmonics
